export const ACCOUNTS_REQUEST = 'ACCOUNTS_REQUEST'
export const ACCOUNTS_SUCCESS = 'ACCOUNTS_SUCCESS'
export const ACCOUNTS_FAIL = 'ACCOUNTS_FAIL'
export const ACCOUNTS_RESET = 'ACCOUNTS_RESET'

export const ACCOUNT_ADD_REQUEST = 'ACCOUNT_ADD_REQUEST'
export const ACCOUNT_ADD_SUCCESS = 'ACCOUNT_ADD_SUCCESS'
export const ACCOUNT_ADD_FAIL = 'ACCOUNT_ADD_FAIL'
export const ACCOUNT_ADD_RESET = 'ACCOUNT_ADD_RESET'

export const ACCOUNT_DETAILS_REQUEST = 'ACCOUNT_DETAILS_REQUEST'
export const ACCOUNT_DETAILS_SUCCESS = 'ACCOUNT_DETAILS_SUCCESS'
export const ACCOUNT_DETAILS_FAIL = 'ACCOUNT_DETAILS_FAIL'
export const ACCOUNT_DETAILS_RESET = 'ACCOUNT_ADD_RESET'
