export const CAPITAL_REQUEST = 'CAPITAL_REQUEST'
export const CAPITAL_SUCCESS = 'CAPITAL_SUCCESS'
export const CAPITAL_FAIL = 'CAPITAL_FAIL'
export const CAPITAL_RESET = 'CAPITAL_RESET'

export const CAPITAL_UPDATE_REQUEST = 'CAPITAL_UPDATE_REQUEST'
export const CAPITAL_UPDATE_SUCCESS = 'CAPITAL_UPDATE_SUCCESS'
export const CAPITAL_UPDATE_FAIL = 'CAPITAL_UPDATE_FAIL'
export const CAPITAL_UPDATE_RESET = 'CAPITAL_UPDATE_RESET'
