export const CURRENCIES_GET_REQUEST = 'CURRENCIES_GET_REQUEST'
export const CURRENCIES_GET_SUCCESS = 'CURRENCIES_GET_SUCCESS'
export const CURRENCIES_GET_FAIL = 'CURRENCIES_GET_FAIL'
export const CURRENCIES_GET_RESET = 'CURRENCIES_GET_RESET'

export const CURRENCIES_UPDATE_REQUEST = 'CURRENCIES_UPDATE_REQUEST'
export const CURRENCIES_UPDATE_SUCCESS = 'CURRENCIES_UPDATE_SUCCESS'
export const CURRENCIES_UPDATE_FAIL = 'CURRENCIES_UPDATE_FAIL'
export const CURRENCIES_UPDATE_RESET = 'CURRENCIES_UPDATE_RESET'
