export const CURRENCYRATE_ADD_REQUEST = 'CURRENCYRATE_ADD_REQUEST'
export const CURRENCYRATE_ADD_SUCCESS = 'CURRENCYRATE_ADD_SUCCESS'
export const CURRENCYRATE_ADD_FAIL = 'CURRENCYRATE_ADD_FAIL'
export const CURRENCYRATE_ADD_RESET = 'CURRENCYRATE_ADD_RESET'

export const CURRENCYRATE_LIST_REQUEST = 'CURRENCYRATE_LIST_REQUEST'
export const CURRENCYRATE_LIST_SUCCESS = 'CURRENCYRATE_LIST_SUCCESS'
export const CURRENCYRATE_LIST_FAIL = 'CURRENCYRATE_LIST_FAIL'
export const CURRENCYRATE_LIST_RESET = 'CURRENCYRATE_LIST_RESET'

export const CURRENCYRATE_DELETE_REQUEST = 'CURRENCYRATE_DELETE_REQUEST'
export const CURRENCYRATE_DELETE_SUCCESS = 'CURRENCYRATE_DELETE_SUCCESS'
export const CURRENCYRATE_DELETE_FAIL = 'CURRENCYRATE_DELETE_FAIL'
export const CURRENCYRATE_DELETE_RESET = 'CURRENCYRATE_DELETE_RESET'

export const CURRENCYRATE_FINANS_LIST_REQUEST =
  'CURRENCYRATE_FINANS_LIST_REQUEST'
export const CURRENCYRATE_FINANS_LIST_SUCCESS =
  'CURRENCYRATE_FINANS_LIST_SUCCESS'
export const CURRENCYRATE_FINANS_LIST_FAIL = 'CURRENCYRATE_FINANS_LIST_FAIL'
export const CURRENCYRATE_FINANS_LIST_RESET = 'CURRENCYRATE_FINANS_LIST_RESET'
