export const INTERACTION_ADD_REQUEST = 'INTERACTION_ADD_REQUEST'
export const INTERACTION_ADD_SUCCESS = 'INTERACTION_ADD_SUCCESS'
export const INTERACTION_ADD_FAIL = 'INTERACTION_ADD_FAIL'
export const INTERACTION_ADD_RESET = 'INTERACTION_ADD_RESET'

export const INTERACTION_LIST_REQUEST = 'INTERACTION_LIST_REQUEST'
export const INTERACTION_LIST_SUCCESS = 'INTERACTION_LIST_SUCCESS'
export const INTERACTION_LIST_FAIL = 'INTERACTION_LIST_FAIL'
export const INTERACTION_LIST_RESET = 'INTERACTION_LIST_RESET'

export const INTERACTION_ADD_IO_REQUEST = 'INTERACTION_ADD_IO_REQUEST'
export const INTERACTION_ADD_IO_SUCCESS = 'INTERACTION_ADD_IO_SUCCESS'
export const INTERACTION_ADD_IO_FAIL = 'INTERACTION_ADD_IO_FAIL'
export const INTERACTION_ADD_IO_RESET = 'INTERACTION_ADD_IO_RESET'

export const INTERACTION_UPDATE_REQUEST = 'INTERACTION_UPDATE_REQUEST'
export const INTERACTION_UPDATE_SUCCESS = 'INTERACTION_UPDATE_SUCCESS'
export const INTERACTION_UPDATE_FAIL = 'INTERACTION_UPDATE_FAIL'
export const INTERACTION_UPDATE_RESET = 'INTERACTION_UPDATE_RESET'

export const INTERACTION_DETAILS_REQUEST = 'INTERACTION_DETAILS_REQUEST'
export const INTERACTION_DETAILS_SUCCESS = 'INTERACTION_DETAILS_SUCCESS'
export const INTERACTION_DETAILS_FAIL = 'INTERACTION_DETAILS_FAIL'
export const INTERACTION_DETAILS_RESET = 'INTERACTION_DETAILS_RESET'

export const INTERACTION_DELETE_REQUEST = 'INTERACTION_DELETE_REQUEST'
export const INTERACTION_DELETE_SUCCESS = 'INTERACTION_DELETE_SUCCESS'
export const INTERACTION_DELETE_FAIL = 'INTERACTION_DELETE_FAIL'
export const INTERACTION_DELETE_RESET = 'INTERACTION_DELETE_RESET'

export const INTERACTION_LIST_BY_ACCOUNT_REQUEST =
  'INTERACTION_LIST_BY_ACCOUNT_REQUEST'
export const INTERACTION_LIST_BY_ACCOUNT_SUCCESS =
  'INTERACTION_LIST_BY_ACCOUNT_SUCCESS'
export const INTERACTION_LIST_BY_ACCOUNT_FAIL =
  'INTERACTION_LIST_BY_ACCOUNT_FAIL'
export const INTERACTION_LIST_BY_ACCOUNT_RESET =
  'INTERACTION_LIST_BY_ACCOUNT_RESET'

export const INTERACTION_LIST_BY_DATE_REQUEST =
  'INTERACTION_LIST_BY_DATE_REQUEST'
export const INTERACTION_LIST_BY_DATE_SUCCESS =
  'INTERACTION_LIST_BY_DATE_SUCCESS'
export const INTERACTION_LIST_BY_DATE_FAIL = 'INTERACTION_LIST_BY_DATE_FAIL'
export const INTERACTION_LIST_BY_DATE_RESET = 'INTERACTION_LIST_BY_DATE_RESET'

export const INTERACTION_LIST_BY_USER_REQUEST =
  'INTERACTION_LIST_BY_USER_REQUEST'
export const INTERACTION_LIST_BY_USER_SUCCESS =
  'INTERACTION_LIST_BY_USER_SUCCESS'
export const INTERACTION_LIST_BY_USER_FAIL = 'INTERACTION_LIST_BY_USER_FAIL'
export const INTERACTION_LIST_BY_USER_RESET = 'INTERACTION_LIST_BY_USER_RESET'

export const INTERACTION_LIST_BY_TYPE_REQUEST = 'INTERACTION_LIST_TYPE_REQUEST'
export const INTERACTION_LIST_BY_TYPE_SUCCESS =
  'INTERACTION_LIST_BY_TYPE_SUCCESS'
export const INTERACTION_LIST_BY_TYPE_FAIL = 'INTERACTION_LIST_BY_TYPE_FAIL'
export const INTERACTION_LIST_BY_TYPE_RESET = 'INTERACTION_LIST_BY_TYPE_RESET'

export const TOTAL_BY_ACCOUNT_REQUEST = 'TOTAL_BY_ACCOUNT_REQUEST'
export const TOTAL_BY_ACCOUNT_SUCCESS = 'TOTAL_BY_ACCOUNT_SUCCESS'
export const TOTAL_BY_ACCOUNT_FAIL = 'TOTAL_BY_ACCOUNT_FAIL'
export const TOTAL_BY_ACCOUNT_RESET = 'TOTAL_BY_ACCOUNT_RESET'

export const TOTAL_REQUEST = 'TOTAL_REQUEST'
export const TOTAL_SUCCESS = 'TOTAL_SUCCESS'
export const TOTAL_FAIL = 'TOTAL_FAIL'
export const TOTAL_RESET = 'TOTAL_RESET'

export const TOTAL_PRIMARY_REQUEST = 'TOTAL_PRIMARY_REQUEST'
export const TOTAL_PRIMARY_SUCCESS = 'TOTAL_PRIMARY_SUCCESS'
export const TOTAL_PRIMARY_FAIL = 'TOTAL_PRIMARY_FAIL'
export const TOTAL_PRIMARY_RESET = 'TOTAL_PRIMARY_RESET'
